{% set name = "nsls2forge-utils" %}
{% set version = "0.1.2" %}
{% set sha256 = "025fcf30ddf0f5f6ce6badd7080dc305ac110b3cbdf87b70b4c731a7d4dafbde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - all-feedstocks = nsls2forge_utils.cli:all_feedstocks
    - auto-tick = nsls2forge_utils.cli:auto_tick
    - check-results = nsls2forge_utils.cli:check_results
    - dashboard = nsls2forge_utils.cli:dashboard
    - graph-utils = nsls2forge_utils.cli:graph_utils
    - meta-utils = nsls2forge_utils.cli:meta_utils
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - beautifulsoup4
    - doctr
    - github3.py
    - gitpython
    - markdown
    - networkx
    - pandas
    - pygithub
    - requests
    - tabulate
    - xonsh

test:
  requires:
    - git
  imports:
    - nsls2forge_utils
  commands:
    - check-results --help

about:
  home: https://github.com/nsls-ii-forge/nsls2forge-utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: nsls2forge utilities for packaging
