{% set name = "nsls2forge-utils" %}
{% set version = "0.0.2" %}
{% set sha256 = "1f594a4f8e28e5dd936a999b3fd425ee185d43543ade1d88428c85021ac7b587" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - check-results = nsls2forge_utils.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nsls2forge_utils
  commands:
    - check-results --help

about:
  home: https://github.com/nsls-ii-forge/nsls2forge-utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: nsls2forge utilities for packaging
